EstudiosSocioeconomicos/Controllers/EstudiosSocioEconomicosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EstudiosSocioeconomicos.Models;
using EstudiosSocioeconomicos.Models.ViewModel;
using Microsoft.AspNet.Identity;

namespace EstudiosSocioeconomicos.Controllers
{
    public class EstudiosSocioEconomicosController : Controller
    {

        EstSocEcoModelContainer bd = new EstSocEcoModelContainer();
        // GET: EstudiosSocioEconomicos
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Encuestadores()
        {
            return View();
        }
        public JsonResult View_Encuestadores()
        {
            //string s_data = null;

            List<EncuestadoresViewModel> s_data = new List<EncuestadoresViewModel>();
            s_data = bd.Encuestadores.Select(x => new EncuestadoresViewModel
            {
                Nombre = x.Nombre
                ,ApellidoPaterno = x.ApellidoPaterno
                ,ApellidoMaterno = x.ApellidoMaterno
                ,IsActive = x.IsActive

            }).ToList();
            
            var data = Json(s_data, JsonRequestBehavior.AllowGet);
            data.MaxJsonLength = int.MaxValue;
            return data;
        }
        public ActionResult Encuestas()
        {
            return View();
        }
        public JsonResult View_Encuestas()
        {
            List<EncuestasViewModel> s_data = new List<EncuestasViewModel>();

            s_data = bd.Encuestas.Select(x => new EncuestasViewModel{ 

                Nombre = x.Nombre
                ,ApellidoPaterno = x.ApellidoPaterno
                ,ApellidoMaterno = x.ApellidoMaterno
                ,IsActive = x.IsActive
                ,Encuestadores_Id = x.Encuestadores_Id
                ,AsingEncuestor = x.AsingEncuestor
                ,s_CreateRow = x.CreateRow == null ? "No se ha Registrado":x.CreateRow.ToString()
                ,s_ActiveCount = x.ActiveCount == null ? "No se ha Registrado" :x.ActiveCount.ToString()
                ,s_DesactiveCount = x.DesactiveCount == null ? "No se ha Registrado" :x.DesactiveCount.ToString()
                ,s_UpdateCount = x.UpdateCount == null ? "No se ha Registrado" :x.UpdateCount.ToString()

            }).ToList();

            var data = Json(s_data, JsonRequestBehavior.AllowGet);
            data.MaxJsonLength = int.MaxValue;
            return data;
        }
    }
}

EstudiosSocioeconomicos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <script src="https://use.fontawesome.com/a0e50c9721.js"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Aministración Encuestadores", "Index", "EstudiosSocioEconomicos", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "EstudiosSocioEconomicos")</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Encuestadores", "Encuestadores", "EstudiosSocioEconomicos")</li>
                        <li>@Html.ActionLink("Encuestas", "Encuestas", "EstudiosSocioEconomicos")</li>

                        <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                        <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>